{% set name = "django-debug-toolbar" %}
{% set version = "4.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9204050fcb1e4f74216c5b024bc76081451926a6303993d6c513f5e142675927

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - django >=4.2.9
    - sqlparse >=0.2

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A configurable set of panels that display various debug information about the current request/response

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
